spring:
  application:
    name: order-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:course}
    password: ${RABBITMQ_PASSWORD:course}
management:
  endpoints:
    web:
      exposure:
        include: health,info
notification:
  base-url: ${NOTIFICATION_BASE_URL:http://localhost:8000}